# FROM node:14.16.0:alpine
FROM public.ecr.aws/bitnami/node:14-prod-debian-10
# FROM public.ecr.aws/bitnami/node:14.16.0-debian-10-r8
# FROM public.ecr.aws/bitnami/node:14.15.1-debian-10-r8

# RUN mkdir /app

WORKDIR  /app

COPY package.json .

COPY prisma ./prisma/

# Install app dependencies
RUN npm install
# Generate prisma client, leave out if generating in `postinstall` script
# RUN npx prisma generate
# RUN npm install
COPY . . 

RUN npm run build

EXPOSE 80

CMD [ "npm", "run", "start"]